### ISSUE TITLE
separate flag-icons.css 

### ISSUE THREAD

**Issue by NaMax66** [VirtoCommerce/vc-theme-b2b-vue#817]
styles from file flag-icons.css go into the general style.css file. This significantly increases its size

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8462 has been created

**Comment by ivan-kalachikov** [comment]
I can be separated simply by using dynamic import

```js
import("flag-icons/css/flag-icons.min.css");
```

But what exactly we want to achieve doing that? Do we aim some performance metrics improvement? If so, we probably need something else but mere separating.

**Comment by ivan-kalachikov** [comment]
Suggest to use Emojis instead of images:
https://dev.to/jorik/country-code-to-flag-emoji-a21

There is a concern on flag emojis on Windows (they are not available for some political reasons). But it can be easily solved with polyfill: https://github.com/talkjs/country-flag-emoji-polyfill

By using this approach we significantly decrease the bundle size thus improve performance metrics.
Disadvantage is not consistent view (depends on user's OS).
